// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
Table Account_Role { 
  AccountRoleId int 
  AccountRoleName varchar
}

Table Account {
  UserUUID uuid
  UserFName varchar
  UserLName varchar
  CreatedOn timestamp 
  AccountRoleId int 
  isActive bit 
}

Table ResponseTeam {
  ResponseTeamId uuid 
  ResponseTeamDescription text 
  ResponseTeamName varchar
}

Table ResponseTeam_Account { 
  UserUUID uuid 
  ResponseTeamId uuid
}

Table Event_Type { 
  EventTypeId serial [pk]
  EventTypeName varchar
  EventTypeDesc TEXT
}

Table Event_Status { 
  EventStatusId serial [pk]
  EventStatusName varchar 
  EventStatusDesc TEXT
}

Table Event { 
  EventId uuid [pk] 
  EventTypeId int 
  EventName varchar
  EventStatusId int 
  CommanderUserUUID uuid
  EventSeverityId int 
}

Table Event_Severity { 
  EventSeverityId serial [pk]
  EventSeverityLevel varchar 
  EventSeverityDescription varchar
}

Table Event_Timeline { 
  EventId uuid
  TimelineId uuid [pk] 
  TimelineNoteId varchar 
  TimelineEntryTypeId int 
  EnteredByUserUUID uuid
  CreatedOn timestamp
}

Table Event_Timeline_Entry_Type {
  TimelineEntryTypeId serial [pk] 
  TimelineEntryTypeName varchar
  TimelineEntryTypeDesc text 
}

Table Event_Timeline_Notes { 
  TimelineNoteId uuid 
  TimelineId uuid [pk] 
  EntryNote text
}
